### ISSUE TITLE
ERROR: Could not create an instance for type Comment

### ISSUE THREAD

**Issue by mhermosi** [evermeer/EVWordPressAPI#1]
for the following piece of code:

self.api = EVWordPressAPI(wordpressOauth2Settings: self.wordpressOauth2Settings, site:        self.wordpressSite)
print("getting posts list max number: ", limit)
self.api.posts([.number(limit)]) { posts in
     print("===============")
     print(posts)
}

I have the this output error:

2016-04-19 19:30:58.392 ApplicationName[79388:871847] ERROR: Could not create an instance for type Comment
2016-04-19 19:30:58.392 ApplicationName[79388:871847] ERROR: Could not create an instance for type Comment

"==============="
Optional(Comments {
   hash = 137412099064211
   key = comments, value = (
)
   key = message, value = <null>
   key = found, value = 2
   key = error, value = <null>
   key = site_ID, value = 1
}
)

**Comment by evermeer** [comment]
Could you tell me for what site you are trying this? When I run this code against my site (evict.nl) It does not fail.

**Comment by mhermosi** [comment]
Hi Edwin,

I’m trying against my site, www.sismos.cl http://www.sismos.cl/. I tried forking your code and after doing some changes (I’m using latest Xcode and swift 2.0) I have added a test case
and was able to get the comments (I modified EVObject because of swift 2.0) so I’m lost why the call to obtain comments is failing on my project.

/**
Object that will support NSCoding, Printable, Hashable and Equeatable for all properties. Use this object as your base class instead of NSObject and you wil automatically have support for all these protocols.
_/
public class EVObject: NSObject, NSCoding /_, CustomDebugStringConvertible */ { // These are redundant in Swift 2: CustomStringConvertible, Hashable, Equatable

Thanks in Advance,

Martin Hermosilla G.
mhermosi@gmail.com
+1 (415) 513 - 9850

**Comment by evermeer** [comment]
Strange, that update for Swift 2.0 is already in EVReflection (EVObject) I will have a look this evening why you get the old version.

**Comment by mhermosi** [comment]
I have noticed…

Let me clarify:

the problem is on my project Sismos en Chile.

I have cloned your repo to add a test case for comments. and the only glitch there was that I had to update the EVObject as I mention before. but when I ran my the
test case added by me boom it worked. So I got really confused.

Best,

Martin Hermosilla G.
mhermosi@gmail.com
+1 (415) 513 - 9850
